from api_client import APIClient



# Replace with the token generated by the PHP script
TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vd2luZGVwbG95LmxvY2FsLmFwaSIsImlhdCI6MTc3MjU2NTQ2MSwiZXhwIjoxNzcyNTc5ODYxLCJuYmYiOjE3NzI1NjU0NjEsImp0aSI6ImVObnZvYkJKeUswRzdhRGkiLCJzdWIiOiIxIiwid2l6YXJkX2lkIjoxLCJtYWNfYWRkcmVzcyI6ImFhOmJiOmNjOmRkOmVlOmZmIiwidHlwZSI6ImFnZW50In0.bsYy8Lz2GnXgydRsqHw7e6j6oA-WM-Mp4ldJog-Mim8'

client = APIClient(base_url='http://127.0.0.1:8000/api', timeout=30)
client.set_token(TOKEN)

# Minimal wizard_config (authenticate previously in UI flow); empty dict is accepted
wizard_config = {}

resp = client.start_execution(wizard_config)
print('status_code=', resp.status_code)
try:
    print('json=', resp.json())
except Exception as e:
    print('text=', resp.text)
